version: '3'
services:
  dnd-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # enviornment:
    #   - NODE_ENV=development
    command: npm run dev
