version: '3'
services:
  # pgdb:
  #   image: 'postgres'
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=inventory_app
  #   volumes:
  #     - pgdata1:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U postgres']
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s

  # sequelize-container:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-Sequelize
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=inventory_app
  #   depends_on:
  #     - dnd-app

  dnd-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - PGUSER=ofelix60
      - PGPASSWORD=HeL1piKaY7bW
      - PGDATABASE=neondb
      - PGHOST=ep-late-limit-066898.us-west-2.aws.neon.tech
    depends_on:
      - pgdb
    command: node server.js
# volumes:
#   pgdata1: {}
