version: '3'
services:
  pgdb:
    image: 'postgres'
    healthcheck:
      test: ['cmd-shell', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory_app
    volumes:
      - pgdata1:/var/lib/postgresql/data

  sequelize:
    image: 'sequelize'
    build:
      context: .
      dockerfile: Dockerfile-Sequelize
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory_app
    depends_on:
      - dnd-app

  dnd-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=inventory_app
      - PG_HOST=pgdb
    depends_on:
      - pgdb
    command: node server.js

volumes:
  pgdata1: {}
