version: '3'
services:
  dnd-app:
    build: .
    ports:
      - '8000:8000'
    # enviornment:
    #   - PORT=8000
    # depends_on:
    #   - pgdb

  pgdb:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
    #   - POSTGRES_PASSWORD: postgres
    #   - POSTGRES_USER: postgres
    #   - POSTGRES_DB: inventory_app
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
