FROM node
WORKDIR /usr/app
COPY . .
RUN ["npm", "install", "sequelize"]
RUN ["npm", "install", "--save", "pg", "pg-hstore"]
RUN ["npm", "install", "sequelize-cli"]
# RUN ["npx", "sequelize-cli", "init"] <---
CMD ["npx", "sequelize", "db:seed:all"]
# apt-get install postrgesql-client
