name: Deploy to EC2

on:
  workflow_run:
    workflows: ['Image build/push']
    types:
      - completed
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: default
        service: app-container-service
        region: us-east-1
        task-definition: app-task-definition
        container-name: InventoryContainer
        container-port: 3000
        # ghcr.io/your-username/your-repository:${{ github.sha }}
        image:
          [
            'ghcr.io/ofelix60/inventory-app_server:main',
            'ghcr.io/ofelix60/inventory-app_client:main',
          ]
        wait-for-service-stability: true
