name: Deploy to EC2

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: your-docker-image
          tags: latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: aws-actions/ec2-instance-control@v1
        with:
          region: us-east-1
          instance-ids: i-1234567890abcdefg
          wait-until-running: true
          action: start
      - name: Deploy Docker container
        uses: docker/deploy-to-ecs-action@v1
        with:
          registry-url: docker.pkg.github.com
          repository: docker.pkg.github.com/your-user/your-docker-image
          region: us-east-1
          cluster: your-cluster
          service: your-service
          force-new-deployment: true
